name: "alump's i2c Sensors"
description: "Reads values for entities from local i2c sensors"
version: "0.2.25"
slug: "sht30_sensor"
url: https://github.com/alump/alump-sht30
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
log_level: info
startup: services
privileged:
  - SYS_ADMIN
devices:
  - /dev/i2c-1
device_tree: true
homeassistant_api: true
map:
  - config:rw
options:
  temperature_entity_id: sensor.sht30_temperature
  humidity_entity_id: sensor.sht30_humidity
  send_interval: 30
  samples: 10
  temperature_decimals: 2
  humidity_decimals: 1
schema:
  temperature_entity_id: str
  humidity_entity_id: str
  send_interval: int(1,86400)
  samples: int(1,86400)
  temperature_decimals: int(0,5)
  humidity_decimals: int(0,3)
